name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests openai

      - name: Debug: Check if OPEN_API_KEY is set
        run: |
          if [ -z "$OPEN_API_KEY" ]; then
            echo "❌ OPEN_API_KEY is NOT set"
            exit 1
          else
            echo "✅ OPEN_API_KEY is set"
          fi
        env:
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}

      - name: Run AI code review
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
        run: |
          python scripts/review_pr.py
